"""Generate Round 2b action-menu variants.

These variants keep the current objective and SOC reserve schedule intact.
They only change which battery actions the optimizer is allowed to consider.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "strategy_task1.py"
OUT_DIR = Path(__file__).resolve().parent


OLD_DISCHARGE_BLOCK = """            battery_options.update(
                {
                    min(discharge_cap_mw, 10.0),
                    min(discharge_cap_mw, 20.0),
                    min(discharge_cap_mw, 30.0),
                    min(discharge_cap_mw, 40.0),
                    min(discharge_cap_mw, 50.0),
                    min(discharge_cap_mw, deficit_mw),
                }
            )
"""


OLD_SHOULD_DISCHARGE = """        should_discharge = (
            price >= 430.0
            or pre_action_import_mw >= costs.grid_max_import_mw - 10.0
        )
"""


def render_discharge_block(
    step_mw: float,
    *,
    import_targets: tuple[float, ...] = (),
) -> str:
    fixed_values = []
    value = step_mw
    while value <= 50.0 + 1e-9:
        fixed_values.append(value)
        value += step_mw

    fixed_lines = "\n".join(
        f"                    min(discharge_cap_mw, {value:.1f}),"
        for value in fixed_values
    )

    target_lines = ""
    if import_targets:
        targets = ", ".join(f"{target:.1f}" for target in import_targets)
        target_lines = f"""
            for target_import_mw in ({targets},):
                target_discharge_mw = max(0.0, pre_action_import_mw - target_import_mw)
                if target_discharge_mw > 0.0:
                    discharge_candidates.add(
                        min(discharge_cap_mw, target_discharge_mw)
                    )
"""

    return f"""            discharge_candidates = {{
{fixed_lines}
                    min(discharge_cap_mw, deficit_mw),
                }}
{target_lines}
            battery_options.update(discharge_candidates)
"""


def render_variant(
    source: str,
    *,
    label: str,
    step_mw: float,
    import_targets: tuple[float, ...] = (),
    price_trigger: float = 430.0,
    import_buffer: float = 10.0,
    cap_factor: float | None = None,
) -> str:
    text = source
    discharge_block = render_discharge_block(
        step_mw,
        import_targets=import_targets,
    )
    text = text.replace(OLD_DISCHARGE_BLOCK, discharge_block)
    text = text.replace(
        OLD_SHOULD_DISCHARGE,
        f"""        should_discharge = (
            price >= {price_trigger:.1f}
            or pre_action_import_mw >= costs.grid_max_import_mw - {import_buffer:.1f}
        )
""",
    )
    if cap_factor is not None:
        text = text.replace(
            "return self._clip(1.6 * sustainable_mw, 10.0, costs.max_inverter_mw)",
            f"return self._clip({cap_factor:.2f} * sustainable_mw, 10.0, costs.max_inverter_mw)",
        )

    header = (
        f"# Local sweep variant: Round 2b action menu {label}\n"
        "# Generated by scratch/task1_variants/generate_action_round2b.py\n\n"
    )
    return header + text


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    variants = {
        "strategy_task1_mvround2b_action000.py": {
            "label": "5MW discharge steps",
            "step_mw": 5.0,
        },
        "strategy_task1_mvround2b_action001.py": {
            "label": "2.5MW discharge steps",
            "step_mw": 2.5,
        },
        "strategy_task1_mvround2b_action002.py": {
            "label": "target imports 95/100/102",
            "step_mw": 10.0,
            "import_targets": (95.0, 100.0, 102.0),
        },
        "strategy_task1_mvround2b_action003.py": {
            "label": "target imports 90/95/100",
            "step_mw": 10.0,
            "import_targets": (90.0, 95.0, 100.0),
        },
        "strategy_task1_mvround2b_action004.py": {
            "label": "5MW steps + target imports 95/100/102",
            "step_mw": 5.0,
            "import_targets": (95.0, 100.0, 102.0),
        },
        "strategy_task1_mvround2b_action005.py": {
            "label": "5MW steps + target imports 90/95/100",
            "step_mw": 5.0,
            "import_targets": (90.0, 95.0, 100.0),
        },
        "strategy_task1_mvround2b_action006.py": {
            "label": "2.5MW steps + target imports 95/100/102",
            "step_mw": 2.5,
            "import_targets": (95.0, 100.0, 102.0),
        },
        "strategy_task1_mvround2b_action007.py": {
            "label": "2.5MW steps + target imports 90/95/100",
            "step_mw": 2.5,
            "import_targets": (90.0, 95.0, 100.0),
        },
        "strategy_task1_mvround2b_action008.py": {
            "label": "5MW steps lower price trigger",
            "step_mw": 5.0,
            "price_trigger": 410.0,
        },
        "strategy_task1_mvround2b_action009.py": {
            "label": "5MW steps earlier import trigger",
            "step_mw": 5.0,
            "import_buffer": 20.0,
        },
        "strategy_task1_mvround2b_action010.py": {
            "label": "5MW steps cap factor 1.4",
            "step_mw": 5.0,
            "cap_factor": 1.4,
        },
        "strategy_task1_mvround2b_action011.py": {
            "label": "5MW steps cap factor 1.8",
            "step_mw": 5.0,
            "cap_factor": 1.8,
        },
    }

    for filename, params in variants.items():
        path = OUT_DIR / filename
        path.write_text(render_variant(source, **params), encoding="utf-8")

    print(f"wrote {len(variants)} Round 2b action variants to {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
