"""Generate local-only task 1 strategy variants for playtest sweeps.

The generated strategy files are experiment scaffolding. The submission
candidate remains ../../strategy_task1.py.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "strategy_task1.py"
OUT_DIR = Path(__file__).resolve().parent


def render_variant(
    source: str,
    *,
    label: str,
    price_trigger: float | None = None,
    import_buffer: float | None = None,
    cap_factor: float | None = None,
    midday_soc: float | None = None,
    pre_peak_soc: float | None = None,
    peak_soc: float | None = None,
    default_soc: float | None = None,
    pre_peak_start: int | None = None,
    pre_peak_end: int | None = None,
    peak_start: int | None = None,
    peak_end: int | None = None,
    soc_weight: float | None = None,
    demand_weight: float | None = None,
    ramp_weight: float | None = None,
    battery_wear_weight: float | None = None,
) -> str:
    text = source

    if price_trigger is not None:
        text = text.replace("price >= 430.0", f"price >= {price_trigger:.1f}")
    if import_buffer is not None:
        text = text.replace(
            "pre_action_import_mw >= costs.grid_max_import_mw - 10.0",
            f"pre_action_import_mw >= costs.grid_max_import_mw - {import_buffer:.1f}",
        )
    if cap_factor is not None:
        text = text.replace(
            "return self._clip(1.6 * sustainable_mw, 10.0, costs.max_inverter_mw)",
            f"return self._clip({cap_factor:.2f} * sustainable_mw, 10.0, costs.max_inverter_mw)",
        )

    if midday_soc is not None:
        text = text.replace("return 0.98", f"return {midday_soc:.2f}")
    if pre_peak_soc is not None:
        text = text.replace("return 0.45", f"return {pre_peak_soc:.2f}")
    if peak_soc is not None:
        text = text.replace("return 0.08", f"return {peak_soc:.2f}")
    if default_soc is not None:
        text = text.replace("return 0.05", f"return {default_soc:.2f}")
    if pre_peak_start is not None or pre_peak_end is not None:
        start = 63 if pre_peak_start is None else pre_peak_start
        end = 66 if pre_peak_end is None else pre_peak_end
        text = text.replace("if 63 <= time_of_day <= 66:", f"if {start} <= time_of_day <= {end}:")
    if peak_start is not None or peak_end is not None:
        start = 67 if peak_start is None else peak_start
        end = 86 if peak_end is None else peak_end
        text = text.replace("if 67 <= time_of_day <= 86:", f"if {start} <= time_of_day <= {end}:")

    if soc_weight is not None:
        text = text.replace(
            "self.soc_reserve_penalty = 1500000.0",
            f"self.soc_reserve_penalty = {soc_weight:.1f}",
        )
    if demand_weight is not None:
        text = text.replace("self.demand_charge = 1.0", f"self.demand_charge = {demand_weight:.2f}")
    if ramp_weight is not None:
        text = text.replace("self.ramp_charge = 1.0", f"self.ramp_charge = {ramp_weight:.2f}")
    if battery_wear_weight is not None:
        text = text.replace("self.battery_wear = 1.0", f"self.battery_wear = {battery_wear_weight:.2f}")

    header = f"# Local sweep variant: {label}\n# Generated by scratch/task1_variants/generate_variants.py\n\n"
    return header + text


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    variants = {
        "strategy_task1_mvbaseline.py": {"label": "current strategy_task1.py"},
        "strategy_task1_mvbatch1_variant000.py": {
            "label": "batch1 price=420 buffer=10 cap=1.60",
            "price_trigger": 420.0,
            "import_buffer": 10.0,
            "cap_factor": 1.60,
        },
        "strategy_task1_mvbatch1_variant001.py": {
            "label": "batch1 price=410 buffer=10 cap=1.60",
            "price_trigger": 410.0,
            "import_buffer": 10.0,
            "cap_factor": 1.60,
        },
        "strategy_task1_mvbatch1_variant002.py": {
            "label": "batch1 price=430 buffer=15 cap=1.60",
            "price_trigger": 430.0,
            "import_buffer": 15.0,
            "cap_factor": 1.60,
        },
        "strategy_task1_mvbatch1_variant003.py": {
            "label": "batch1 price=430 buffer=5 cap=1.60",
            "price_trigger": 430.0,
            "import_buffer": 5.0,
            "cap_factor": 1.60,
        },
        "strategy_task1_mvbatch1_variant004.py": {
            "label": "batch1 price=430 buffer=10 cap=1.40",
            "price_trigger": 430.0,
            "import_buffer": 10.0,
            "cap_factor": 1.40,
        },
        "strategy_task1_mvbatch1_variant005.py": {
            "label": "batch1 price=430 buffer=10 cap=1.80",
            "price_trigger": 430.0,
            "import_buffer": 10.0,
            "cap_factor": 1.80,
        },
        "strategy_task1_mvbatch2_variant000.py": {
            "label": "batch2 midday=1.00 pre=0.45 peak=0.08",
            "midday_soc": 1.00,
            "pre_peak_soc": 0.45,
            "peak_soc": 0.08,
        },
        "strategy_task1_mvbatch2_variant001.py": {
            "label": "batch2 midday=0.98 pre=0.35 peak=0.08",
            "midday_soc": 0.98,
            "pre_peak_soc": 0.35,
            "peak_soc": 0.08,
        },
        "strategy_task1_mvbatch2_variant002.py": {
            "label": "batch2 midday=0.98 pre=0.55 peak=0.08",
            "midday_soc": 0.98,
            "pre_peak_soc": 0.55,
            "peak_soc": 0.08,
        },
        "strategy_task1_mvbatch2_variant003.py": {
            "label": "batch2 midday=0.98 pre=0.45 peak=0.12",
            "midday_soc": 0.98,
            "pre_peak_soc": 0.45,
            "peak_soc": 0.12,
        },
        "strategy_task1_mvbatch2_variant004.py": {
            "label": "batch2 earlier pre-peak window",
            "pre_peak_start": 60,
            "pre_peak_end": 66,
        },
        "strategy_task1_mvbatch2_variant005.py": {
            "label": "batch2 shorter peak window",
            "peak_start": 68,
            "peak_end": 84,
        },
        "strategy_task1_mvbatch3_variant000.py": {
            "label": "batch3 soc_weight=1.0m",
            "soc_weight": 1000000.0,
        },
        "strategy_task1_mvbatch3_variant001.py": {
            "label": "batch3 soc_weight=2.0m",
            "soc_weight": 2000000.0,
        },
        "strategy_task1_mvbatch3_variant002.py": {
            "label": "batch3 demand_weight=1.25",
            "demand_weight": 1.25,
        },
        "strategy_task1_mvbatch3_variant003.py": {
            "label": "batch3 demand_weight=1.50",
            "demand_weight": 1.50,
        },
        "strategy_task1_mvbatch3_variant004.py": {
            "label": "batch3 ramp_weight=0.50",
            "ramp_weight": 0.50,
        },
        "strategy_task1_mvbatch3_variant005.py": {
            "label": "batch3 battery_wear_weight=0.50",
            "battery_wear_weight": 0.50,
        },
        "strategy_task1_mvcombo_variant000.py": {
            "label": "combo best batch2 + soc_weight=2.0m",
            "midday_soc": 1.00,
            "soc_weight": 2000000.0,
        },
        "strategy_task1_mvcombo_variant001.py": {
            "label": "combo best batch2 + battery_wear_weight=0.50",
            "midday_soc": 1.00,
            "battery_wear_weight": 0.50,
        },
        "strategy_task1_mvcombo_variant002.py": {
            "label": "combo best batch2 + soc_weight=2.0m + battery_wear_weight=0.50",
            "midday_soc": 1.00,
            "soc_weight": 2000000.0,
            "battery_wear_weight": 0.50,
        },
    }

    for filename, params in variants.items():
        path = OUT_DIR / filename
        path.write_text(render_variant(source, **params), encoding="utf-8")

    print(f"wrote {len(variants)} variants to {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
