"""Generate Round 1 value-function-only variants.

Round 1 keeps the action menu unchanged and only adds a future energy value
term to the objective. The point is to learn whether stored SOC valuation helps
before changing candidate generation.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "strategy_task1.py"
OUT_DIR = Path(__file__).resolve().parent


def render_variant(
    source: str,
    *,
    filename: str,
    value_per_mwh: float,
    start_tod: int,
    end_tod: int,
) -> str:
    text = source
    text = text.replace(
        '            "soc_reserve_penalty": self.soc_reserve_penalty(state, physics),\n',
        '            "soc_reserve_penalty": self.soc_reserve_penalty(state, physics),\n'
        '            "future_energy_value": self.future_energy_value(state, physics),\n',
    )

    method = f'''
    def future_energy_value(
        self, state: dict[str, Any], physics: dict[str, float]
    ) -> float:
        """Reward keeping deliverable SOC for the configured future peak window."""
        time_of_day = int(state.get("time", 0)) % 96
        if time_of_day > {end_tod}:
            return 0.0

        deliverable_mwh = (
            physics["next_soc"]
            * self.ACTION_COSTS.battery_capacity_mwh
            * self.ACTION_COSTS.discharge_efficiency
        )

        if time_of_day < {start_tod}:
            urgency = 1.0
        else:
            remaining = max(1, {end_tod} - time_of_day + 1)
            full_window = max(1, {end_tod} - {start_tod} + 1)
            urgency = remaining / full_window

        return -deliverable_mwh * {value_per_mwh:.1f} * urgency

'''
    text = text.replace(
        "\n    def desired_soc_floor(self, state: dict[str, Any]) -> float:\n",
        "\n" + method + "    def desired_soc_floor(self, state: dict[str, Any]) -> float:\n",
    )

    header = (
        f"# Local sweep variant: Round 1 value function {filename}\n"
        f"# future_value=${value_per_mwh:.0f}/MWh window={start_tod}-{end_tod}\n"
        "# Generated by scratch/task1_variants/generate_value_round1.py\n\n"
    )
    return header + text


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    windows = [(67, 86), (74, 84), (76, 82)]
    values = [250.0, 350.0, 450.0, 550.0]

    count = 0
    for window_i, (start_tod, end_tod) in enumerate(windows):
        for value_i, value_per_mwh in enumerate(values):
            filename = f"strategy_task1_mvround1_value{count:03d}.py"
            rendered = render_variant(
                source,
                filename=filename,
                value_per_mwh=value_per_mwh,
                start_tod=start_tod,
                end_tod=end_tod,
            )
            (OUT_DIR / filename).write_text(rendered, encoding="utf-8")
            count += 1

    print(f"wrote {count} Round 1 value variants to {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
