# Local sweep variant: batch5 hold 0.20 until tod 76
# Generated by scratch/task1_variants/generate_variants.py

"""Task 1 strategy scaffold for the duck_curve scenario.

This file defines the controller shape, state-machine plumbing, and local
objective/cost functions. Dispatch logic can be added once we decide how to
search candidate actions.
"""

from __future__ import annotations

from enum import Enum
from typing import Any


class Mode(str, Enum):
    OBSERVE = "observe"
    DISPATCH = "dispatch"


class ControllerMemory:
    def __init__(self) -> None:
        self.mode: Mode = Mode.OBSERVE
        self.last_time: int | None = None
        self.last_soc: float | None = None
        self.last_net_grid_power_mw: float | None = None
        self.last_objective_terms: dict[str, float] = {}
        self.last_objective_score: float = 0.0


class ObjectiveWeights:
    def __init__(self) -> None:
        self.blackout_penalty = 20.0
        self.overvoltage_penalty = 10.0
        self.demand_charge = 1.0
        self.tariff_import = 1.0
        self.tariff_export = 1.0
        self.generator_fuel = 1.0
        self.battery_wear = 1.0
        self.carbon_cost = 1.0
        self.ramp_charge = 1.0
        self.soc_reserve_penalty = 1500000.0

    def get(self, name: str, default: float = 1.0) -> float:
        return float(getattr(self, name, default))


class ActionCosts:
    def __init__(self) -> None:
        self.dt_hours = 0.25
        self.battery_capacity_mwh = 100.0
        self.max_inverter_mw = 50.0
        self.grid_max_import_mw = 120.0
        self.grid_max_export_mw = 50.0
        self.charge_efficiency = 0.95
        self.discharge_efficiency = 0.95
        self.max_diesel_mw = 50.0

        self.export_tariff_per_mwh = 50.0
        self.diesel_cost_per_mwh = 1000.0
        self.blackout_penalty_per_mwh = 100000.0
        self.overvoltage_penalty_per_mwh = 5000.0
        self.battery_wear_per_mwh = 50.0
        self.demand_charge_per_mw = 1000.0
        self.carbon_price_per_kg = 50.0
        self.default_grid_co2_kg_per_mwh = 0.7
        self.diesel_co2_kg_per_mwh = 0.27
        self.duck_curve_ramp_charge_per_mw2 = 0.01


class Strategy:
    """Boilerplate Strategy lifecycle accepted by the playtest runner."""

    ACTION_COSTS = ActionCosts()
    OBJECTIVE_WEIGHTS = ObjectiveWeights()

    def __init__(self) -> None:
        self.memory = ControllerMemory()

    def plan(self, state: dict[str, Any]) -> dict[str, Any]:
        self._observe(state)
        return {"agent_plan": {"task": "duck_curve"}}

    def replan(
        self, state: dict[str, Any], alerts: list[dict[str, Any]]
    ) -> dict[str, Any]:
        self._observe(state)
        return {"agent_plan": {"task": "duck_curve", "alerts_seen": len(alerts)}}

    def step(self, state: dict[str, Any]) -> dict[str, float]:
        self._observe(state)
        self.memory.mode = Mode.DISPATCH
        action = self.choose_action(state)
        self.memory.last_objective_terms = self.objective_terms(state, action)
        self.memory.last_objective_score = self.objective_score(state, action)
        return action

    def _observe(self, state: dict[str, Any]) -> None:
        demand = float(state.get("demand", 0.0))
        solar = float(state.get("solar", 0.0))

        self.memory.last_time = int(state.get("time", 0))
        self.memory.last_soc = float(state.get("soc", 0.0))
        self.memory.last_net_grid_power_mw = demand - solar

    @staticmethod
    def _empty_action() -> dict[str, float]:
        return {
            "battery_flow_mw": 0.0,
            "emergency_generator": 0.0,
            "curtail_solar": 0.0,
            "fcas_reserve_mw": 0.0,
        }

    def objective_score(
        self,
        state: dict[str, Any],
        action: dict[str, float],
        weights: ObjectiveWeights | None = None,
    ) -> float:
        terms = self.objective_terms(state, action)
        active_weights = self.OBJECTIVE_WEIGHTS if weights is None else weights
        return sum(active_weights.get(name, 1.0) * value for name, value in terms.items())

    def choose_action(self, state: dict[str, Any]) -> dict[str, float]:
        candidates = self.generate_candidate_actions(state)
        return min(candidates, key=lambda action: self.objective_score(state, action))

    def generate_candidate_actions(self, state: dict[str, Any]) -> list[dict[str, float]]:
        demand = float(state.get("demand", 0.0))
        solar = float(state.get("solar", 0.0))
        soc = self._clip(float(state.get("soc", 0.0)), 0.0, 1.0)
        costs = self.ACTION_COSTS

        surplus_mw = solar - demand
        deficit_mw = demand - solar
        price = float(state.get("price", 0.0))
        pre_action_import_mw = max(0.0, demand - solar)

        battery_options = {0.0}

        if surplus_mw > 0.0 and soc < 0.98:
            battery_options.update(
                {
                    -10.0,
                    -20.0,
                    -30.0,
                    -40.0,
                    -50.0,
                    -min(costs.max_inverter_mw, surplus_mw),
                }
            )

        should_discharge = (
            price >= 430.0
            or pre_action_import_mw >= costs.grid_max_import_mw - 10.0
        )
        if deficit_mw > 0.0 and soc > 0.05 and should_discharge:
            discharge_cap_mw = self.discharge_cap_for_peak(state, soc)
            battery_options.update(
                {
                    min(discharge_cap_mw, 10.0),
                    min(discharge_cap_mw, 20.0),
                    min(discharge_cap_mw, 30.0),
                    min(discharge_cap_mw, 40.0),
                    min(discharge_cap_mw, 50.0),
                    min(discharge_cap_mw, deficit_mw),
                }
            )

        candidates: list[dict[str, float]] = []
        for battery_mw in sorted(battery_options):
            feasible_battery_mw = self.feasible_battery_power(battery_mw, soc)
            raw_net_without_diesel = demand - solar - feasible_battery_mw
            diesel_needed_mw = max(
                0.0, raw_net_without_diesel - costs.grid_max_import_mw
            )
            diesel_options = {0.0}
            if diesel_needed_mw > 0.0:
                diesel_options.add(min(costs.max_diesel_mw, diesel_needed_mw))

            for diesel_mw in sorted(diesel_options):
                raw_net_without_curtail = demand - solar - feasible_battery_mw - diesel_mw
                curtail_needed_mw = max(
                    0.0, -raw_net_without_curtail - costs.grid_max_export_mw
                )
                curtail_options = {0.0}
                if curtail_needed_mw > 0.0:
                    curtail_options.add(min(solar, curtail_needed_mw))

                for curtail_mw in sorted(curtail_options):
                    candidates.append(
                        {
                            "battery_flow_mw": float(battery_mw),
                            "emergency_generator": float(diesel_mw),
                            "curtail_solar": float(curtail_mw),
                            "fcas_reserve_mw": 0.0,
                        }
                    )

        return candidates or [self._empty_action()]

    def objective_terms(
        self, state: dict[str, Any], action: dict[str, float]
    ) -> dict[str, float]:
        physics = self.estimate_physics(state, action)
        costs = self.ACTION_COSTS
        dt = costs.dt_hours

        import_mwh = physics["import_mw"] * dt
        export_mwh = physics["export_mw"] * dt
        diesel_mwh = physics["diesel_mw"] * dt
        battery_mwh = abs(physics["battery_mw"]) * dt

        grid_co2 = float(
            state.get("grid_co2_intensity", costs.default_grid_co2_kg_per_mwh)
        )
        co2_kg = import_mwh * grid_co2 + diesel_mwh * costs.diesel_co2_kg_per_mwh

        terms = {
            "blackout_penalty": (
                physics["unmet_demand_mw"] * dt * costs.blackout_penalty_per_mwh
            ),
            "overvoltage_penalty": (
                physics["overvoltage_mw"] * dt * costs.overvoltage_penalty_per_mwh
            ),
            "demand_charge": physics["new_peak_import_delta_mw"]
            * costs.demand_charge_per_mw,
            "tariff_import": import_mwh * float(state.get("price", 0.0)),
            "tariff_export": -export_mwh * costs.export_tariff_per_mwh,
            "generator_fuel": diesel_mwh * costs.diesel_cost_per_mwh,
            "battery_wear": battery_mwh * costs.battery_wear_per_mwh,
            "carbon_cost": co2_kg * costs.carbon_price_per_kg,
            "ramp_charge": self.ramp_charge(state, physics["net_grid_power_mw"]),
            "soc_reserve_penalty": self.soc_reserve_penalty(state, physics),
        }
        return {name: float(value) for name, value in terms.items()}

    def estimate_physics(
        self, state: dict[str, Any], action: dict[str, float]
    ) -> dict[str, float]:
        demand = float(state.get("demand", 0.0))
        solar = float(state.get("solar", 0.0))
        soc = self._clip(float(state.get("soc", 0.0)), 0.0, 1.0)
        costs = self.ACTION_COSTS

        requested_battery_mw = float(action.get("battery_flow_mw", 0.0))
        battery_mw = self.feasible_battery_power(requested_battery_mw, soc)
        next_soc = self.next_soc(soc, battery_mw)

        diesel_mw = self._clip(
            float(action.get("emergency_generator", 0.0)), 0.0, costs.max_diesel_mw
        )
        curtail_solar_mw = self._clip(
            float(action.get("curtail_solar", 0.0)), 0.0, solar
        )

        actual_solar_mw = solar - curtail_solar_mw
        raw_net_grid_power_mw = demand - actual_solar_mw - battery_mw - diesel_mw

        unmet_demand_mw = max(0.0, raw_net_grid_power_mw - costs.grid_max_import_mw)
        overvoltage_mw = max(
            0.0, -raw_net_grid_power_mw - costs.grid_max_export_mw
        )
        net_grid_power_mw = self._clip(
            raw_net_grid_power_mw,
            -costs.grid_max_export_mw,
            costs.grid_max_import_mw,
        )

        import_mw = max(0.0, net_grid_power_mw)
        export_mw = max(0.0, -net_grid_power_mw)
        peak_import_mw = float(state.get("peak_import_mw", 0.0))

        return {
            "battery_mw": battery_mw,
            "diesel_mw": diesel_mw,
            "curtail_solar_mw": curtail_solar_mw,
            "next_soc": next_soc,
            "raw_net_grid_power_mw": raw_net_grid_power_mw,
            "net_grid_power_mw": net_grid_power_mw,
            "import_mw": import_mw,
            "export_mw": export_mw,
            "unmet_demand_mw": unmet_demand_mw,
            "overvoltage_mw": overvoltage_mw,
            "new_peak_import_delta_mw": max(0.0, import_mw - peak_import_mw),
        }

    def feasible_battery_power(self, requested_mw: float, soc: float) -> float:
        costs = self.ACTION_COSTS
        clipped_mw = self._clip(
            requested_mw, -costs.max_inverter_mw, costs.max_inverter_mw
        )

        if clipped_mw > 0.0:
            max_discharge_mw = (
                soc * costs.battery_capacity_mwh * costs.discharge_efficiency
            ) / costs.dt_hours
            return min(clipped_mw, max_discharge_mw)

        if clipped_mw < 0.0:
            headroom_mwh = (1.0 - soc) * costs.battery_capacity_mwh
            max_charge_mw = headroom_mwh / (
                costs.charge_efficiency * costs.dt_hours
            )
            return max(clipped_mw, -max_charge_mw)

        return 0.0

    def next_soc(self, soc: float, battery_mw: float) -> float:
        costs = self.ACTION_COSTS
        if battery_mw > 0.0:
            next_soc = soc - (battery_mw * costs.dt_hours) / (
                costs.battery_capacity_mwh * costs.discharge_efficiency
            )
        elif battery_mw < 0.0:
            next_soc = soc - (
                battery_mw * costs.charge_efficiency * costs.dt_hours
            ) / costs.battery_capacity_mwh
        else:
            next_soc = soc

        return self._clip(next_soc, 0.0, 1.0)

    def ramp_charge(self, state: dict[str, Any], net_grid_power_mw: float) -> float:
        prev_grid = state.get("prev_grid_power_mw")
        if prev_grid is None:
            return 0.0
        ramp_mw = net_grid_power_mw - float(prev_grid)
        return (
            ramp_mw
            * ramp_mw
            * self.ACTION_COSTS.duck_curve_ramp_charge_per_mw2
        )

    def soc_reserve_penalty(
        self, state: dict[str, Any], physics: dict[str, float]
    ) -> float:
        target = self.desired_soc_floor(state)
        shortfall = max(0.0, target - physics["next_soc"])
        return shortfall * shortfall

    def desired_soc_floor(self, state: dict[str, Any]) -> float:
        time_of_day = int(state.get("time", 0)) % 96
        day = int(state.get("time", 0)) // 96
        solar = float(state.get("solar", 0.0))
        demand = float(state.get("demand", 0.0))

        if 40 <= time_of_day <= 62 and solar > demand:
            return 1.00
        if 63 <= time_of_day <= 66:
            return 0.45
        if 67 <= time_of_day <= 76:
            return 0.20
        if 77 <= time_of_day <= 86:
            return 0.05
        return 0.05

    @staticmethod
    def is_peak_window(state: dict[str, Any]) -> bool:
        time_of_day = int(state.get("time", 0)) % 96
        return 64 <= time_of_day <= 86

    def discharge_cap_for_peak(self, state: dict[str, Any], soc: float) -> float:
        costs = self.ACTION_COSTS
        if not self.is_peak_window(state):
            return costs.max_inverter_mw

        time_of_day = int(state.get("time", 0)) % 96
        remaining_steps = max(1, 83 - time_of_day)
        deliverable_mwh = soc * costs.battery_capacity_mwh * costs.discharge_efficiency
        sustainable_mw = deliverable_mwh / (remaining_steps * costs.dt_hours)
        return self._clip(1.6 * sustainable_mw, 10.0, costs.max_inverter_mw)

    @staticmethod
    def _clip(value: float, low: float, high: float) -> float:
        return max(low, min(high, value))


if __name__ == "__main__":
    from watt_the_hack.playtest import run_playtest

    result = run_playtest(__file__, "duck_curve", plots=True, open_report=False)
    print(f"\nRaw cost (lower wins): ${result['metrics']['final_score']:,.2f}")
